services:

  message:
    image: "rabbitmq:3.13"
  
    ports:
    - "5672:5672"
  
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    env_file:
      - path: ./.env.default
        required: true
      - path: ./.env.local
        required: false

  database:
    image: "postgres:16"

    ports:
      - "5432:5432"
    volumes:
      - ./database/volume:/var/lib/postgresql/data
    env_file:
      - path: ./.env.default
        required: true
      - path: ./.env.local
        required: false

  web:
    image: "leroysalih/lts-web:0.9"
      
    ports:
      - "3000:3000"
    depends_on:
      message:
        condition : service_healthy

    volumes:
      - /Users/leroysalih/Long-task-svr/web:/app
      
    env_file:
      - path: ./.env.default
        required: true
      - path: ./.env.local
        required: false


  worker:
    image: "leroysalih/lts-worker:0.3"

    depends_on:
      message:
        condition : service_healthy

    volumes:
      - /Users/leroysalih/Long-task-svr/worker:/app
    env_file:
      - path: ./.env.default
        required: true
      - path: ./.env.local
        required: false

  

  


  